# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("SparseBayes"); Pkg.test("SparseBayes"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SparseBayes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
